version: '3'
services:
  papermc:
    build: build
    ports:
      - 25565:25565
    volumes:
      - ./data:/opt/mc
    restart: always
  frpc:
    image: fatedier/frpc:v0.44.0
    volumes:
      - ./frpc.ini:/opt/frpc.ini
    command: -c /opt/frpc.ini
    restart: always
    depends_on:
      - papermc
